# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-19 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='passcode',
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user_id',
            field=models.TextField(max_length=600),
        ),
    ]
